name = "SortTileRecursiveTree"
uuid = "746ee33f-1797-42c2-866d-db2fce69d14d"
authors = ["Max Freudenberg <maximilian.freudenberg@uni-goettingen.de> and contributors"]
version = "0.1.1"

[deps]
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[weakdeps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
STRTreeRecipesBaseExt = "RecipesBase"

[compat]
julia = "1.6"
Extents = "0.1.0"
GeoInterface = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
